sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t brahste/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brahste/react-test npm test

after_success:
  - docker build -t brahste/multi-client ./client
  - docker build -t brahste/multi-nginx ./nginx
  - docker build -t brahste/multi-server ./server
  - docker build -t brahste/multi-worker ./worker
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push brahste/multi-client
  - docker push brahste/multi-nginx
  - docker push brahste/multi-server
  - docker push brahste/multi-worker

